### ISSUE TITLE
Any type of screenshots or demo

### ISSUE THREAD

**Issue by MACscr** [venturedrake/laravel-crm#22]
How functional is the current codebase? Are you looking for contributors? Do you have any screenshots of the existing system? I guess I could just install it to find out, but wanted to find out a bit more about its current state, etc, first.

**Comment by andrewdrake** [comment]
I released 0.1.0 as it was the bare min function in a CRM. that being ability to manage contacts, leads, deals, users and teams.  My plan however is to rapidly add to this and move towards what I believe are all the core parts of a CRM

- Products
- Notes
- Tasks
- Files / Documents
- Calendar (Calls, Meetings, Reminders)
- Roles / Permissions
- Dashboard
- Custom Fields
- Activity Feed / Timelines
- CSV Import / Export

There is actually much more than the above planned, however this I would see as being an "MVP" for any CRM. I've built custom enterprise CRMs for years and am pulling my experience from this to develop this opensource project

Yes looking for contributors :) Although I've been in the PHP dev game since 1998 I've never been involved in an Opensource project. So this my first and would love to work with contributors and learn how the process works at the same time. 

Here is a screenshot with dummy data. The front end is not styled yet, rather plain bootstrap but I will work on that soon also. Main focus is backend at the moment. 

![image](https://user-images.githubusercontent.com/2742557/112066559-ae564780-8bba-11eb-94eb-b3796d8af1da.png)

**Comment by andrewdrake** [comment]
Hi @MACscr,

Closing this ticket for now. Package under heavy development so keep an eye on updates!

Andrew
