### ISSUE TITLE
Laravel Auth / Jetstream

### ISSUE THREAD

**Issue by safarovitch** [venturedrake/laravel-crm#32]
### Question
Does the package support jetsream or laravel auth or do we need both?

### Description:
I see the documentation is not clear about if we need to isntall both laravel auth and jetstream.
The package clearly requires laravel auth. But when installing both laravel auth and Jetstream in order to use teams functionality the installation will not work properly.

### Steps To Reproduce:
Fresh install Laravel current stable version.
Install laravel auth as mentioned in docs.
Install Jetstream.
Install laravel-crm
Run the app and try to register
**Throws error**
ErrorException
Attempt to read property "currentTeam" on null

**Comment by andrewdrake** [comment]
Thanks for reporting this, looks like a bug. Will get it fixed asap for you. 

The package is designed for Laravel 6, 7 and 8 with or without Jetstream. Auth is installed with Jetstream so only need Auth installed when not using Jetstream. To use Teams, yes will need Laravel 8 & Jetstream.

Sorry this isn't clear, we are working on the laravelcrm.com site which will have complete docs as we approach production ready version 1 release.

**Comment by andrewdrake** [comment]
Sorry just getting back to this, when you install Ketstream is also contains the laravel auth features, so you don't need to install both. Since Laravel 8 there are "starter kits" Breeze and Jetstream, and I haven't looked at Breeze myself just yet. 

The easiest thing for me to do her is work on the command line installer, which will give you the options of what you want to install in a fresh Laravel installation. 

The bug that you were experienced is actually also fixed so we can close this ticket.
